<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Mods\mod</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSSurvivalMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSEssentials">
      <HintPath>$(VINTAGE_STORY)/Mods/VSEssentials.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="VSCreativeMod">
      <HintPath>$(VINTAGE_STORY)/Mods/VSCreativeMod.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(VINTAGE_STORY)/Lib/Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="protobuf-net">
      <HintPath>$(VINTAGE_STORY)/Lib/protobuf-net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\**">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="assets\hardcorewater\blocktypes\stone\stonebrick\enclosedaqueduct.json" />
    <None Remove="assets\hardcorewater\blocktypes\wood\woodtyped\aqueduct.json" />
    <None Remove="assets\hardcorewater\config\handbook\aqueducts.json" />
    <None Remove="assets\hardcorewater\lang\en.json" />
    <None Remove="assets\hardcorewater\recipes\grid\aqueduct.json" />
    <None Remove="assets\hardcorewater\recipes\grid\enclosedaqueduct.json" />
    <None Remove="assets\hardcorewater\recipes\grid\woodaqueduct.json" />
    <Content Include="modinfo.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
